# list:
alias ls='ls -CF --color=auto'
alias ll='ls -lha'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

# folders:
alias cdd='cd ../..'
alias cddd='cd ../../..'

# typos:
alias cd..='cd ..'
alias sl='ls'

# shortening:
alias c='clear'
alias h='history'

# sudo:
alias root='sudo -i'
alias su='sudo -i'

# grep:
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias grepi='grep -ri'
alias greph='grep -ri --exclude-dir=".*"'
alias gn='grep -ri --exclude="*.ipynb"'

# git:
alias gdd='git add'
alias glg='git log --oneline --decorate --graph --all'
alias gst='git status'
alias gco='git checkout'
alias gcm='git commit'

# jupyter:
alias jpn='jupyter notebook &'
alias jpl='jupyter lab &'
alias jpx='jupyter lab --no-browser'

# vscode:
alias codei='code --ignore-certificate-errors'

# vim:
alias vim='nvim'
alias vi='nvim'

# misc:
alias df='df -Tha --total'
alias du='du -ach | sort -h'
alias untar='tar -zxvf '
alias sha='shasum -a 256 '
alias ipi='ipconfig getifaddr en0'
